* 前言
深圳，中国四大一线城市之一；国贸，深圳市中心的中心。独自一人漫步于金光华广场，身边一个又一个西装革履的男士擦肩而过，肝胆相照的兄弟却越来越少；随身而过一个又一个浓妆性感的女孩，却再没有没有上学时那种倾之以心，相伴永远的的感觉！偶然之间看到自己两年前的笔迹，却还是那种感觉。
有人说无人知晓的孤独，是每个生命体的必修课。从上学到现在，大部分的时候都是自己一个人走过无锡、深圳、广州、湛江、北京、成都、上海，碾转于不同的城市，讲述自己的故事。有人说成长就是穿越光阴，把一切软肋变成铠甲，酸甜苦辣，人情冷暖，故事很精彩，但是却无人分享。
上周末出去玩儿瀑降的时候遇见了一个姑娘，那是许久不曾有过的心动，我知道这次我一定不能错过，即使没有结果也一定不能让自己后悔！爱情的力量是伟大的，她说我对你不了解啊。想起自己平时偶尔打的没有形成的草稿，正好趁这个机会整理一个，送给自己心爱的姑娘，也送给深圳许久不见的兄弟们。

* 现在的自己

去年12月份的时候，有一次往家里打电话，那天爸爸说了好多，好多我都不记得了，只记得一句:我对你很失望!
电话挂了，一个人默默地做饭、吃饭、听歌，望着上海万家璀璨的灯火，一个人默默地流泪。
上次流泪是初二的时候。为了测试自己的勇气，我想去坟地睡一晚上，但是被爸妈锁在了屋里。不管怎么敲他们就是不开门，那天晚上我在床上哭了一夜，从此再也没有了眼泪。现在回想起来当时确实太极端了，只是没有想到十年之后泪水再次汹涌不已。
痛苦有时候是一种提升，否则，我们流的眼泪也就毫无意义。
从那天开始我每天5点多起床不需要闹钟。早上的时间真好，没有人打扰，可以静下心来看书。就这样2018的半年，读完加看完的书有8本，到现在已经11本了。
每天12点半到1点睡觉，然后第二天5点多起床甚至不到5点。一个月后我怕了：这样搞下去早晚有一个自己的身体和精神都得崩溃!
于是我把睡眠时间提前到10点半到11点。又开始健身，一开始每天3公里都跑得气喘吁吁，现在半个小时跑6公里多然后继续在健身房玩儿其它的项目。体重也从去年12月的169，到现在最低142。
如今大半年过去了，跑步、健身、早起、看书、练技术早已成了习惯

* 人生是没有停止的战斗
很小的时候就听过一个故事：
从前有一种鸟儿是没有脚的，它的一生只能不停地飞啊，飞啊，飞啊，飞累了就在风里面休息，在风里面睡觉，这种鸟一生只能落地一次，那一次就是它死亡的时刻。
好多时候都觉得自己就像这只鸟，
还没有毕业就孤身一人去了深圳，还没有到深圳差点被传销骗到韶关，到了以后，在深圳大学的长椅上睡了三天之后终于下找到住的地方。
技术不足，毕业证还没有发，面试过多少场记不清了，后来算了一下自己笔记过的有37场！找到工作的那天，多日的阴霾终于雨过天晴。
刚刚挣点钱，就连着遇到诈骗，其中一个还是集团的同事。
在广州遇见自己一个很喜欢的姑娘，不顾一切地冲向广东金融学院，归来一片残阳。
转行做大数据，在深圳这个吸一口气都需要钱的城市里半年没有工作&#x2026;幸亏当时做投资的朋友的帮助，才一点一点地渡过难关。
直到转战上海生活才算是顺利了点儿，前几天在健身房里教练给我做拉伸训练，她一直说：疼了就说，疼了就说&#x2026;到最后她都不敢给我拉了，怕把我的韧带拉断!酸甜苦辣，人生百味，经历得多了，难道连我的身体也都已经麻木了?
没事的时候最喜欢的音乐就是女子十二乐坊的《十面埋伏》，每每听到这首轻音乐，就会想起以前走投无路的时刻，人生突围的时刻。
原来这就是筚路蓝缕，这就是峥嵘岁月！
回顾过往，转专业，去深圳，转做大数据，玩儿金融，转战上海，其实都是命运的巨变。只是当时站在命运三岔路口，眼见风云千樯，在作出抉择的那一日，在日记本上，相当的沉闷和平凡，当时还以为是生命中普通的一天。


* 人生规划

上学的时候好多同学都说我很有毅力，确实，能坚持做8年的俯卧撑、仰卧起坐;坚持两年每天下午跑步，确实很有毅力。但是如果自己说的话，是胆略志，'胆'毋庸置疑。'略'这一路起来自己应该还是有点眼光的吧。'志'也还行吧。
最喜欢的两本书:《孙子兵法》《三国演义》
不知道是小学五年级还是六年级，看中了一本《孙子兵法》36元的定价对于当时的自己简直是天价，省吃简用了好多最后终于背着爸妈偷偷地把它买了下来。
没事儿的时候就翻出来看看，不知道看了多少遍了，有时候看着天边的流云，就会下意识地来两句:计利以听乃为之势，以佐其外，势者因利而制权也&#x2026;。就像好多人没事的时候喜欢哼歌一样。读得多了，自然应该有些谋略吧。
小学五年级的时候，特别想让爸爸给自己买一本《奥特曼》结果大姐给我买了半文言文的《三国演义》上中下三本，说:"你把它看完，我给你买《奥特曼》"。看着《三国演义》密密麻麻的文言文就头皮发麻，不过为了我心爱的奥特曼后来还是把它们看完了。看完了，奥特曼也不要了，到了初中的时候《三国演义》看得已经不下10遍了。
特喜欢曹操的"对酒当歌，人生几何"，"老骥伏枥，志在千里"。最喜欢刘备从织席少年到割据一方的人生经历。或许从那个时候就有了出门闯天下的志了吧。


* 做自己
周国平的《无论走多远你终将面对自己》书名就道出了自己的心声，买下来后才发现是写给中学生的，但是我还是把它给看完了。只因为这个书名。
毕业四年，终于挣了点，我终于可以做点自己想做的事情了。但是了解过自己的梦想以后，心情却哇凉哇凉的。原来自己所谓的战略，所谓的人生规则早已遗落在了大学。
我搞程序，也玩儿金融，但是我知道金融不过是为程序服务的。一年就设想着:从金融赚80万，作为出国留学的学费，去卡耐基梅隆大学留学学习人工智能。然后在谷歌工作几年，回国创业。但是，其实一开始的时候我就不具备留学的资格:出国留学是要大学的成绩单的。
命运真的是开了个不大不小的玩笑:以区区小钱，就买断了自己所有的梦想和人生规划!原来这就是我自以为是的战略!
原来这就是无论走多远你终将面对的自己。


