* 概述
我在亚马逊EC2云服务器上建的有SSR，和Mysql服务，今天一上班突然发现连不上Mysql了！
再试了试SecureCRT仿真终端,也连不上EC2实例的终端,又Ping了下,也ping不通,这个EC2实例是一个多月前创建的,地点选的是韩国首尔,云服务器放在国外,便于fan_墙,又离国内近.用得一直好好的,Mysql服务啦,翻qiang啦都是没有问题的,上周五的时候我还连,周末的时候出去玩儿了一圈回来,就出现这种情况了.其实之前的时候也出现过类似的情况，当时还以为是因为翻墙被封了呢,没有办法只好再创建一个实例了,也就是现在这个.
OK,出了问题就解决一下吧.
*问题描述*
亚马逊云服务器ec２连不上也ping不通

问题解决以后,回过头来看其实是可以分为三个具体的问题的?
1. EC2实例连不上
2. EC2实例ping不通
3. EC2实例是否被封
因为EC2实例上Mysql服务,终端连不上与ping不通走的入站规则是不一样的,连不上与ping不通是两个不同的问题

* EC2实例连不上
一般来说云服务器有问题,重启一下云服务器,或者停止-启动一下,两种的效果是不一样的,后者代价更大,IP地址会变,我的云服务器重启后就正常的了,如果你的还不行,就联系客服吧.
* EC2实例ping不通
这里是官网的介绍:
[[https://docs.aws.amazon.com/zh_cn/AWSEC2/latest/UserGuide/TroubleshootingInstancesConnecting.html#troubleshoot-instance-ping][无法对实例执行ping操作]]
说得很详细,简单来说就是如果你想ping通EC2实例的话需要单独设置入站规则.
怎么设置呢?
在EC2 Dashboard选择安全组选项卡,选中要修改的安全组选择入站规则(Inbound)-编辑-添加规则 
类型选择自定义ICMP规则,
选择请求(Echo Request),
来源选择任何位置.
然后点击保存,就可以Ping就能ping通了

* 真的被封了吗
朋友的云服务器是在日本的,一直用着都没事,我的怎么老被封啊?每次被封就重新创建一个EC2实例,这个成本也太高了,得先确认一下是不是真的被封了.
用站长工具检测一下,网址:http://ping.chinaz.com/
在输入框输入你的IP地址或者域名,检测范围全选,然后点击ping检测

如果国内的正常,国外的也正常,说明你的云服务器正常,当然这是费话,不需要讨论,
如果国内的超时,国外不超时,说明你确实被墙了,
如果国内的超时,国外的也超时,说明你的安全组设置得有问题,或者你的云服务器有问题.
安全组设置有问题,参考上面的[[EC2实例ping不通]]
云服务器有问题,参考上面[[EC2实例连不上]]
